### PR TITLE
This device supports Night Display

### PR DESCRIPTION
**Pull request by zacharee**
- Tested by manually editing framework-res.apk

### CODE REVIEW

**Comment by luk1337** [comment]
1. Use Gerrit
2. We have Live Display this isn't necessary

**Comment by luk1337** [comment]
1. Check wiki
2. That's unfortunate but still I am not going to enable something that duplicates what live display is supposed to do.

**Comment by zacharee** [comment]
1. OK. Will do.
2. This change doesn't add the Night Display option to Settings. It just enables the functionality.

**Comment by luk1337** [comment]
There's only one device that has this enabled and that's Pixel thus I am not going to accept this change.

**Comment by zacharee** [comment]
I don't understand that reasoning, but OK.

**Comment by luk1337** [comment]
image
As you can see here this isn't widely accepted change as it simply duplicates Live Display functionality.

**Comment by zacharee** [comment]
But why not just add it? It isn't like it adds 200MB more to the system image.

**Comment by luk1337** [comment]
Because we already have Live Display. If you really want this then build your own system images.

**Comment by zacharee** [comment]
I'm just decompiling the framework-res.apk. Thought it might be helpful to have.

**Comment by lineageos-gerrit** [comment]
Hi there;
This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
