### PR TITLE
Add lock screen auto rotation.

### PR DESCRIPTION
**Pull request by wangling12**
This is important for tablets.

### CODE REVIEW

**Comment by wangling12** [comment]
It looks like this needs to use Gerrit. But because of the network, I need hundreds of hours to repo sync here. Just a line of code, I hope you can help me submit this.

**Comment by luca020400** [comment]
Checkout lineage-push https://github.com/LineageOS/scripts
It allows pushing changes to review checking out only one project at time

**Comment by wangling12** [comment]
Thank you. I'll try it.

**Comment by srccrow** [comment]
Port LineageOS 18.1 instead.

**Pull request closed without merging**
